name: MirCleaveNet
channels:
  - bioconda
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=main
  - _tflow_select=2.1.0=gpu
  - astor=0.8.0=py37_0
  - blas=1.0=mkl
  - c-ares=1.15.0=h7b6447c_1001
  - ca-certificates=2025.7.15=h06a4308_0
  - certifi=2022.12.7=py37h06a4308_0
  - cudatoolkit=10.0.130=0
  - cudnn=7.6.4=cuda10.0_0
  - cupti=10.0.130=0
  - cycler=0.10.0=py37_0
  - dbus=1.13.12=h746ee38_0
  - et_xmlfile=1.1.0=py37h06a4308_0
  - expat=2.2.6=he6710b0_0
  - fontconfig=2.13.0=h9420a91_0
  - freetype=2.9.1=h8a8886c_1
  - gast=0.2.2=py37_0
  - glib=2.63.1=h5a9c865_0
  - google-pasta=0.1.8=py_0
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb453b48_1
  - h5py=2.9.0=py37h7918eee_0
  - hdf5=1.10.4=hb1b8bf9_0
  - icu=58.2=h9c2bf20_1
  - intel-openmp=2019.4=243
  - jpeg=9b=h024ee3a_2
  - keras-applications=1.0.8=py_0
  - keras-gpu=2.2.4=0
  - keras-preprocessing=1.1.0=py_1
  - kiwisolver=1.1.0=py37he6710b0_0
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libpng=1.6.37=hbc83047_0
  - libprotobuf=3.10.1=hd408876_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libuuid=1.0.3=h1bed415_2
  - libxcb=1.13=h1bed415_1
  - libxml2=2.9.9=hea5a465_1
  - markdown=3.1.1=py37_0
  - matplotlib=3.1.1=py37h5429711_0
  - mkl=2019.4=243
  - mkl-service=2.3.0=py37he904b0f_0
  - mkl_fft=1.0.15=py37ha843d7b_0
  - mkl_random=1.1.0=py37hd6b4f25_0
  - ncurses=6.1=he6710b0_1
  - openpyxl=3.0.9=pyhd3eb1b0_0
  - openssl=1.1.1w=h7f8727e_0
  - pandas=0.25.3=py37he6710b0_0
  - pcre=8.43=he6710b0_0
  - pip=19.3.1=py37_0
  - pyparsing=2.4.5=py_0
  - pyqt=5.9.2=py37h05f1152_2
  - python=3.7.5=h0371630_0
  - python-dateutil=2.8.1=py_0
  - pytz=2019.3=py_0
  - pyyaml=5.1.2=py37h7b6447c_0
  - qt=5.9.7=h5867ecd_1
  - readline=7.0=h7b6447c_5
  - scipy=1.3.1=py37h7c811a0_0
  - setuptools=42.0.1=py37_0
  - sip=4.19.8=py37hf484d3e_0
  - sqlite=3.30.1=h7b6447c_0
  - tensorflow-gpu=1.15.0=h0d30ee6_0
  - termcolor=1.1.0=py37_1
  - tk=8.6.8=hbc83047_0
  - tornado=6.0.3=py37h7b6447c_0
  - viennarna=2.4.14=py37h8b12597_0
  - webencodings=0.5.1=py37_1
  - wheel=0.33.6=py37_0
  - wrapt=1.11.2=py37h7b6447c_0
  - xlwt=1.3.0=py37_0
  - xz=5.2.4=h14c3975_4
  - yaml=0.1.7=had09818_2
  - zlib=1.2.11=h7b6447c_3
  - pip:
      - absl-py==2.1.0
      - aiohttp==3.8.6
      - aiosignal==1.3.1
      - altair==5.0.1
      - annotated-types==0.5.0
      - anyio==3.7.1
      - astunparse==1.6.3
      - async-timeout==4.0.3
      - asynctest==0.13.0
      - attrs==19.3.0
      - babel==2.14.0
      - backcall==0.1.0
      - backports-zoneinfo==0.2.1
      - bce-python-sdk==0.9.29
      - biopython==1.81
      - bleach==3.1.0
      - blinker==1.6.3
      - cachetools==5.5.2
      - charset-normalizer==3.4.1
      - click==8.1.8
      - cloudpickle==1.2.2
      - colorama==0.4.6
      - colorlog==6.9.0
      - datasets==2.13.2
      - decorator==4.4.1
      - defusedxml==0.6.0
      - dill==0.3.4
      - entrypoints==0.3
      - exceptiongroup==1.3.0
      - fastapi==0.103.2
      - filelock==3.12.2
      - flask==2.2.5
      - flask-babel==2.0.0
      - flatbuffers==25.2.10
      - frozenlist==1.3.3
      - fsspec==2023.1.0
      - future==0.18.2
      - gitdb==4.0.12
      - gitpython==3.1.45
      - google-auth==2.39.0
      - google-auth-oauthlib==0.4.6
      - grpcio==1.62.3
      - h11==0.14.0
      - httpcore==0.17.3
      - httpx==0.24.1
      - huggingface-hub==0.16.4
      - hyperas==0.4.1
      - hyperopt==0.2.2
      - idna==3.10
      - importlib-metadata==6.7.0
      - ipykernel==5.1.3
      - ipython==7.10.0
      - ipython-genutils==0.2.0
      - ipywidgets==7.5.1
      - itsdangerous==2.1.2
      - jedi==0.15.1
      - jieba==0.42.1
      - jinja2==2.10.3
      - joblib==0.14.0
      - jsonschema==3.2.0
      - jupyter==1.0.0
      - jupyter-client==5.3.4
      - jupyter-console==6.0.0
      - jupyter-core==4.6.1
      - keras==2.11.0
      - keras-contrib==2.0.8
      - libclang==18.1.1
      - markdown-it-py==2.2.0
      - markupsafe==2.1.5
      - match==0.3.2
      - mdurl==0.1.2
      - mistune==0.8.4
      - more-itertools==7.2.0
      - multidict==6.0.5
      - multiprocess==0.70.12.2
      - nbconvert==5.6.1
      - nbformat==4.4.0
      - networkx==2.2
      - nltk==3.8.1
      - notebook==6.0.2
      - numpy==1.21.6
      - oauthlib==3.2.2
      - opt-einsum==3.3.0
      - packaging==23.2
      - paddle-bfloat==0.1.7
      - paddle2onnx==1.1.0
      - paddlefsl==1.1.0
      - paddlenlp==2.5.2
      - paddlepaddle-gpu==2.3.2.post112
      - pandocfilters==1.4.2
      - parso==0.5.1
      - patsy==1.0.1
      - pexpect==4.7.0
      - pickleshare==0.7.5
      - pillow==9.5.0
      - prometheus-client==0.7.1
      - prompt-toolkit==2.0.10
      - protobuf==3.20.0
      - psutil==7.0.0
      - ptyprocess==0.6.0
      - pyarrow==12.0.1
      - pyasn1==0.5.1
      - pyasn1-modules==0.3.0
      - pycryptodome==3.23.0
      - pydantic==2.5.3
      - pydantic-core==2.14.6
      - pydeck==0.8.1b1
      - pygments==2.17.2
      - pympler==1.1
      - pyrsistent==0.15.6
      - pytz-deprecation-shim==0.1.0.post0
      - pyzmq==18.1.1
      - qtconsole==4.6.0
      - rarfile==4.2
      - regex==2024.4.16
      - requests==2.31.0
      - requests-oauthlib==2.0.0
      - rich==13.8.1
      - rsa==4.9.1
      - scikit-learn==0.21.3
      - seaborn==0.12.2
      - send2trash==1.5.0
      - sentencepiece==0.2.0
      - seqeval==0.0.12
      - setuptools-scm==3.4.3
      - shellingham==1.5.4
      - six==1.17.0
      - sklearn==0.0
      - smmap==5.0.2
      - sniffio==1.3.1
      - starlette==0.27.0
      - statannotations==0.7.0
      - statsmodels==0.13.5
      - streamlit==1.23.1
      - tenacity==8.2.3
      - tensorboard==2.11.2
      - tensorboard-data-server==0.6.1
      - tensorboard-plugin-wit==1.8.1
      - tensorflow==2.11.0
      - tensorflow-addons==0.19.0
      - tensorflow-estimator==2.11.0
      - tensorflow-io-gcs-filesystem==0.34.0
      - terminado==0.8.3
      - testpath==0.4.4
      - toml==0.10.2
      - toolz==0.12.1
      - tqdm==4.67.1
      - traitlets==4.3.3
      - typeguard==4.1.2
      - typer==0.15.4
      - typing-extensions==4.7.1
      - tzdata==2025.2
      - tzlocal==4.3.1
      - urllib3==2.0.7
      - uvicorn==0.22.0
      - validators==0.20.0
      - visualdl==2.5.3
      - watchdog==3.0.0
      - wcwidth==0.1.7
      - weblogo==3.7.1
      - werkzeug==2.2.3
      - widgetsnbextension==3.5.1
      - xlsxwriter==3.2.2
      - xxhash==3.5.0
      - yarl==1.9.4
      - zipp==0.6.0
prefix: /data1/yangzhou/anaconda3/envs/Dmc
